apiVersion: v1
kind: PersistentVolume
metadata:
  name: broker-pv-data
  labels:
    component: broker
    function: data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/broker-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: broker-pv-var
  labels:
    component: broker
    function: var
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/broker-var"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: broker
    function: data
  name: broker-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: broker
    function: var
  name: broker-var
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi