apiVersion: v1
kind: PersistentVolume
metadata:
  name: coordinator-pv-data
  labels:
    component: coordinator
    function: data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/coordinator-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coordinator-pv-var
  labels:
    component: coordinator
    function: var
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/coordinator-var"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: coordinator
    function: data
  name: coordinator-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: coordinator
    function: var
  name: coordinator-var
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi