apiVersion: v1
kind: Service
metadata:
  labels:
    app: middlemanager
  name: middlemanager-service
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8091
  selector:
    app: middlemanager