apiVersion: v1
kind: PersistentVolume
metadata:
  name: middlemanager-pv-data
  labels:
    component: middlemanager
    function: data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/middlemanager-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: middlemanager-pv-var
  labels:
    component: middlemanager
    function: var
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/middlemanager-var"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: middlemanager
    function: data
  name: middlemanager-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: middlemanager
    function: var
  name: middlemanager-var
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi