apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: channel
  name: channel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: channel
  template:
    metadata:
      labels:
        app: channel
    spec:
      containers:
      - env:
        image: drunknmster/channel:latest
        imagePullPolicy: ""
        name: channel
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
