apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-7
  labels:
    component: minio7
    function: data7
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/minio7"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-8
  labels:
    component: minio8
    function: data8
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/minio8"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: minio7
    function: data7
  name: minio4-data1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: minio8
    function: data8
  name: minio4-data2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi