apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-1
  labels:
    component: minio1
    function: data1
spec:
  storageClassName: minio-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/minio1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-2
  labels:
    component: minio2
    function: data2
spec:
  storageClassName: minio-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/minio2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: minio1
    function: data1
  name: minio-data1
spec:
  storageClassName: minio-data
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: minio2
    function: data2
  name: minio-data2
spec:
  storageClassName: minio-data
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi