apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-3
  labels:
    component: minio3
    function: data3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/minio3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-4
  labels:
    component: minio4
    function: data4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/minio4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: minio3
    function: data3
  name: minio2-data1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: minio4
    function: data4
  name: minio2-data2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi