apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-5
  labels:
    component: minio5
    function: data5
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/minio5"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-6
  labels:
    component: minio6
    function: data6
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/minio6"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: minio5
    function: data5
  name: minio3-data1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: minio6
    function: data6
  name: minio3-data2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi