apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - http://minio{1...4}-service/data{1...2}
        env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: minio123
        image: minio/minio:RELEASE.2020-06-03T22-13-49Z
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:9000/minio/health/live
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 20
        name: minio4
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /data1
          name: minio4-data1
        - mountPath: /data2
          name: minio4-data2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: minio4-data1
        persistentVolumeClaim:
          claimName: minio4-data1
      - name: minio4-data2
        persistentVolumeClaim:
          claimName: minio4-data2