apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: harbor
  name: harbor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor
  template:
    metadata:
      labels:
        app: harbor
    spec:
      containers:
      - env:
        image: drunknmster/harbor:latest
        imagePullPolicy: ""
        name: harbor
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null