apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
    id: "1"
  name: kafka-broker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "1"
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
          - containerPort: 9092
          env:
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: "kafka-service"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service:2181
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_CREATE_TOPICS
            value: druid_metrics:1:1,vsphere_metrics:1:1,access_log:1:1
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null