apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-pv
    labels:
      component: postgres
      function: data
spec:
    storageClassName: postgres-data
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: "/mnt/data/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
      component: postgres
      function: data
    name: postgres-pv-claim
spec:
    storageClassName: postgres-data
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi